//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class bakiye
    {
        public int id { get; set; }
        public Nullable<int> kart_id { get; set; }
        public Nullable<decimal> kredi_kart_bakiye { get; set; }
        public Nullable<decimal> nakit_bakiye { get; set; }
        public Nullable<decimal> deposito { get; set; }
    
        public virtual kart kart { get; set; }
    }
}
