//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class kart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kart()
        {
            this.bakiye = new HashSet<bakiye>();
        }
    
        public int id { get; set; }
        public Nullable<int> kisi_id { get; set; }
        public Nullable<System.DateTime> verilis_tarihi { get; set; }
        public Nullable<System.DateTime> son_kullanma_tarihi { get; set; }
        public int birey_havuz { get; set; }
        public int cocuk_havuz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bakiye> bakiye { get; set; }
        public virtual kisi kisi { get; set; }
    }
}
