//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class otelEntities : DbContext
    {
        public otelEntities()
            : base("name=otelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bakiye> bakiye { get; set; }
        public virtual DbSet<depo> depo { get; set; }
        public virtual DbSet<depo_stok> depo_stok { get; set; }
        public virtual DbSet<donanim> donanim { get; set; }
        public virtual DbSet<kart> kart { get; set; }
        public virtual DbSet<kisi> kisi { get; set; }
        public virtual DbSet<kisi_durum> kisi_durum { get; set; }
        public virtual DbSet<mekan> mekan { get; set; }
        public virtual DbSet<mekan_depo> mekan_depo { get; set; }
        public virtual DbSet<nakit_ciro> nakit_ciro { get; set; }
        public virtual DbSet<oda> oda { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<personel_depo> personel_depo { get; set; }
        public virtual DbSet<personel_donanim> personel_donanim { get; set; }
        public virtual DbSet<pozisyon> pozisyon { get; set; }
        public virtual DbSet<stok> stok { get; set; }
        public virtual DbSet<stok_ad> stok_ad { get; set; }
        public virtual DbSet<stok_birim> stok_birim { get; set; }
        public virtual DbSet<stok_grup> stok_grup { get; set; }
        public virtual DbSet<tur> tur { get; set; }
        public virtual DbSet<ucret> ucret { get; set; }
    }
}
