//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class oda
    {
        public int id { get; set; }
        public Nullable<int> kisi_id { get; set; }
        public Nullable<System.DateTime> giris_tarihi { get; set; }
        public Nullable<System.DateTime> cikis_tarihi { get; set; }
        public Nullable<decimal> ucret { get; set; }
    
        public virtual kisi kisi { get; set; }
    }
}
